version: '2'
services:
    mongo:
        image: mongo:latest
        entrypoint: "mongod --profile=1 --slowms=1 --logpath=/var/log/mongodb/mongod.log"
        container_name: mongo
        ports:
            - 27017:27017
        volumes:
            - ./volumes/mongo/db:/data/db
            - ./volumes/mongo/logs:/var/log/mongodb
    story-engine :
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: story-engine
        command : [
            "/utils/wait-services.sh",
            "mongo:27017",
            "--",
            "npm", "run", "engine"
        ]
        environment:
            PORT: 27000
        ports:
            - 27000:27000
        links:
            - mongo
        depends_on:
            - mongo