version: '2'
services:
    mongo:
        image: mongo:latest
        container_name: "mongo"
        command: mongod --smallfiles --logpath=/dev/null
        ports:
            - 27017:27017
        volumes:
            - ./volumes/mongo/db:/data/db
            - ./volumes/mongo/logs:/var/log/mongodb
    # story-engine :
    #     build:
    #         context: .
    #         dockerfile: ./Dockerfile
    #     command : [
    #         "npm", "run", "engine"
    #     ]
    #     environment:
    #         PORT: 27000
    #     ports:
    #         - 27000:27000
    #     links:
    #         - mongo
    #     depends_on:
    #         - mongo